### PR TITLE
add impl of Test::mysqld::Multi

### PR DESCRIPTION
**Pull request by shogo82148**
I often uses Test::mysqld with App::Prove::Plugin::MySQLPool.
App::Prove::Plugin::MySQLPool launches -j number of Test::mysqld instances first,
while the launching process is very slow if the number is large.

I think that Test::mysqld should have an interface for creating some Test::mysqld instances at once.
Your kind consideration of this matter would be sincerely appreciated.

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.  Can you make the following changes?

* use the functions provided by Test::mysqld to control the database servers
 * the PR should not includes calls like `exec` or `kill`
* please move the functions into Test::mysqld if it is possible to implement the feature only by adding functions

**Comment by shogo82148** [comment]
Thank you for reviewing.

> please move the functions into Test::mysqld if it is possible to implement the feature only by adding functions

I did.

> use the functions provided by Test::mysqld to control the database servers

I want to call just `exec`, but Test::mysqld has no such function.
(`start` function calls `exec`, while it calls `waitpid` too. I want not to call `waitpid`)

**Comment by kazuho** [comment]
>> please move the functions into Test::mysqld if it is possible to implement the feature only by adding functions
> I did.

Thank you for the changes.

>> use the functions provided by Test::mysqld to control the database servers
> 
> I want to call just exec, but Test::mysqld has no such function.
> (`start` function calls `exec`, while it calls `waitpid` too. I want not to call `waitpid`)

I understand that your code spawns all the MySQL instances, and then waits for the instances to start up.  Does the approach result in non-marginal speed-up compared against when using the `start` function (i.e. doing `fork`-`exec` and wait for each instance)?

If not, please use the `start` function.

If yes, please refactor the `start` function, by splitting its two blocks (i.e. spawn and wait-for-startup) to two functions, and call the functions from your multi-daemon startup code.  Having same logic at two places of the module is a no-go.

**Comment by shogo82148** [comment]
> Does the approach result in non-marginal speed-up compared against when using the start function (i.e. doing fork-exec and wait for each instance)?

Yes.
I refactored.

**Pull request merged**
