### PR TITLE
`mysql_install_db` is obsoluted in MySQL 5.7.

### PR DESCRIPTION
**Pull request by karupanerura**
Should use `mysqld --initialize` instead of `mysql_install_db`.

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.  Can you adjust the code to take the approach below in order to minimize compatibility issues?

* Test::mysqld should never set property: `mysql_install_db` by itself
* if property: `mysql_install_db` is set by the user, then it should be run regardless of the version of the mysql server
* if property: `mysql_install_db` is not set by the user, then `mysqld --initialize` should be called

**Comment by karupanerura** [comment]
Thank you for reviewing.
I fixed it. Is this approach correct?

**Comment by karupanerura** [comment]
@kazuho Do you have time to review it?

**Comment by kazuho** [comment]
@karupanerura Sorry for the delay.  I see [these errors](https://gist.github.com/kazuho/38f132326d7a65bd5382) when running `make test` on OSX with a homebrew-version of MySQL installed (5.6.17).  Can you please look into it?

**Comment by karupanerura** [comment]
Oops. Sorry, I'll check it.

**Pull request merged**
